<?php
/**
 * Title: KNDSB sporttakpagina
 * Slug: kndsb/sport-page
 * Description: Sporttakpagina volgens de vaste Client-First-hiërarchie.
 * Categories: kndsb
 * Keywords: sporttak, programma, contact, nieuws
 * Inserter: true
 */
$sport_placeholder   = esc_url( get_stylesheet_directory_uri() . '/assets/images/sport-hero-placeholder.svg' );
$sponsor_placeholder = esc_url( get_stylesheet_directory_uri() . '/assets/images/sponsor-placeholder.svg' );
?>
<!-- wp:kndsb/layout-section {"align":"full","sectionName":"sport-hero","colorScheme":"white","containerSize":"wide","paddingSize":"none"} -->
<section class="wp-block-kndsb-layout-section alignfull section_sport-hero kndsb-layout-section kndsb-layout-section--white"><div class="padding-global"><div class="container-wide"><div class="padding-section-none"><!-- wp:cover {"url":"<?php echo $sport_placeholder; ?>","dimRatio":35,"overlayColor":"black","className":"kndsb-sport-page__hero"} --><div class="wp-block-cover kndsb-sport-page__hero"><span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-35 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Kies een foto van deze sport" src="<?php echo $sport_placeholder; ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":1,"className":"kndsb-sport-page__title"} --><h1 class="wp-block-heading kndsb-sport-page__title">Voetbal</h1><!-- /wp:heading --></div></div><!-- /wp:cover --></div></div></div></section>
<!-- /wp:kndsb/layout-section -->

<!-- wp:kndsb/layout-section {"align":"full","sectionName":"sport-about","colorScheme":"white","containerSize":"large","paddingSize":"medium"} -->
<section class="wp-block-kndsb-layout-section alignfull section_sport-about kndsb-layout-section kndsb-layout-section--white"><div class="padding-global"><div class="container-large"><div class="padding-section-medium"><!-- wp:group {"className":"kndsb-sport-page__about","layout":{"type":"default"}} --><div class="wp-block-group kndsb-sport-page__about"><!-- wp:heading {"level":2,"className":"kndsb-sport-page__about-title"} --><h2 class="wp-block-heading kndsb-sport-page__about-title">Over voetbal</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Beschrijf hier de sport, de verschillende spelvormen en wat de KNDSB binnen deze discipline organiseert.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:columns {"className":"kndsb-sport-page__information"} --><div class="wp-block-columns kndsb-sport-page__information"><!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"kndsb-sport-page__contact-card"} --><div class="wp-block-group kndsb-sport-page__contact-card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Contact</h3><!-- /wp:heading --><!-- wp:paragraph --><p><strong>Naam contactpersoon</strong><br><a href="mailto:sport@kndsb.nl">sport@kndsb.nl</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"kndsb-sport-page__federation-card"} --><div class="wp-block-group kndsb-sport-page__federation-card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Sportbond en praktische informatie</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Voeg hier de aangesloten bond, competitiegegevens, downloads of andere vaste informatie toe.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --></div></div></div></section>
<!-- /wp:kndsb/layout-section -->

<!-- wp:kndsb/layout-section {"align":"full","sectionName":"sport-program","colorScheme":"white","containerSize":"large","paddingSize":"medium"} -->
<section class="wp-block-kndsb-layout-section alignfull section_sport-program kndsb-layout-section kndsb-layout-section--white"><div class="padding-global"><div class="container-large"><div class="padding-section-medium"><!-- wp:kndsb/sport-program /--></div></div></div></section>
<!-- /wp:kndsb/layout-section -->

<!-- wp:kndsb/layout-section {"align":"full","sectionName":"sport-news","colorScheme":"white","containerSize":"large","paddingSize":"medium"} -->
<section class="wp-block-kndsb-layout-section alignfull section_sport-news kndsb-layout-section kndsb-layout-section--white"><div class="padding-global"><div class="container-large"><div class="padding-section-medium"><!-- wp:heading {"level":2,"className":"kndsb-sport-page__section-title"} --><h2 class="wp-block-heading kndsb-sport-page__section-title">Gerelateerde artikelen</h2><!-- /wp:heading --><!-- wp:kndsb/news-row {"title":"Gerelateerde artikelen","categoryId":0,"postsToShow":4,"showExcerpt":true,"showReadMore":true,"loadMore":false} /--></div></div></div></section>
<!-- /wp:kndsb/layout-section -->

<!-- wp:kndsb/layout-section {"align":"full","sectionName":"sport-sponsors","colorScheme":"blue-white","containerSize":"large","paddingSize":"medium"} -->
<section class="wp-block-kndsb-layout-section alignfull section_sport-sponsors kndsb-layout-section kndsb-layout-section--blue-white"><div class="padding-global"><div class="container-large"><div class="padding-section-medium text-align-center"><!-- wp:heading {"level":2,"className":"kndsb-sport-page__sponsor-title"} --><h2 class="wp-block-heading kndsb-sport-page__sponsor-title">Trotse hoofdsponsor</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Met dank aan de organisaties die deze sporttak ondersteunen.</p><!-- /wp:paragraph --><!-- wp:columns {"className":"kndsb-sport-page__main-sponsor-logos"} --><div class="wp-block-columns kndsb-sport-page__main-sponsor-logos"><!-- wp:column --><div class="wp-block-column"><!-- wp:image {"className":"kndsb-sport-page__main-sponsor-logo"} --><figure class="wp-block-image kndsb-sport-page__main-sponsor-logo"><img src="<?php echo $sponsor_placeholder; ?>" alt="Kies hoofdsponsorlogo"/></figure><!-- /wp:image --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:image {"className":"kndsb-sport-page__main-sponsor-logo"} --><figure class="wp-block-image kndsb-sport-page__main-sponsor-logo"><img src="<?php echo $sponsor_placeholder; ?>" alt="Kies sponsorlogo"/></figure><!-- /wp:image --></div><!-- /wp:column --></div><!-- /wp:columns --></div></div></div></section>
<!-- /wp:kndsb/layout-section -->

<!-- wp:kndsb/layout-section {"align":"full","sectionName":"sport-partners","colorScheme":"red","containerSize":"large","paddingSize":"small"} -->
<section class="wp-block-kndsb-layout-section alignfull section_sport-partners kndsb-layout-section kndsb-layout-section--red"><div class="padding-global"><div class="container-large"><div class="padding-section-small"><!-- wp:columns {"className":"kndsb-sport-page__partner-grid"} --><div class="wp-block-columns kndsb-sport-page__partner-grid"><!-- wp:column --><div class="wp-block-column"><!-- wp:image {"className":"kndsb-sport-page__partner"} --><figure class="wp-block-image kndsb-sport-page__partner"><img src="<?php echo $sponsor_placeholder; ?>" alt="Partnerlogo kiezen"/></figure><!-- /wp:image --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:image {"className":"kndsb-sport-page__partner"} --><figure class="wp-block-image kndsb-sport-page__partner"><img src="<?php echo $sponsor_placeholder; ?>" alt="Partnerlogo kiezen"/></figure><!-- /wp:image --></div><!-- /wp:column --></div><!-- /wp:columns --></div></div></div></section>
<!-- /wp:kndsb/layout-section -->
