( function ( blocks, blockEditor, element, components, data, serverSideRender, i18n ) {
	var el = element.createElement, InspectorControls = blockEditor.InspectorControls, PanelBody = components.PanelBody, TextControl = components.TextControl, RangeControl = components.RangeControl, SelectControl = components.SelectControl, ToggleControl = components.ToggleControl, ColorPalette = components.ColorPalette, URLInput = blockEditor.URLInput;
	blocks.registerBlockType( 'kndsb/news-row', { edit: function ( props ) {
		var a = props.attributes, categories = data.useSelect( function ( select ) { return select( 'core' ).getEntityRecords( 'taxonomy', 'category', { per_page: 100 } ); }, [] ), options = [ { label: i18n.__( 'Alle categorieën', 'kndsb' ), value: 0 } ];
		( categories || [] ).forEach( function ( category ) { options.push( { label: category.name, value: category.id } ); } );
		return el( element.Fragment, {}, el( InspectorControls, {}, el( PanelBody, { title: i18n.__( 'Sectie', 'kndsb' ) },
			el( TextControl, { label: i18n.__( 'Titel', 'kndsb' ), value: a.title, onChange: function ( value ) { props.setAttributes( { title: value } ); } } ), el( ColorPalette, { value: a.accentColor, onChange: function ( value ) { props.setAttributes( { accentColor: value } ); } } ),
			el( RangeControl, { label: i18n.__( 'Aantal', 'kndsb' ), min: 1, max: 12, value: a.postsToShow, onChange: function ( value ) { props.setAttributes( { postsToShow: value } ); } } ), el( RangeControl, { label: i18n.__( 'Eerste berichten overslaan', 'kndsb' ), help: i18n.__( 'Kies 1 als bericht 1 al uitgelicht staat.', 'kndsb' ), min: 0, max: 12, value: a.postOffset || 0, onChange: function ( value ) { props.setAttributes( { postOffset: value } ); } } ), el( SelectControl, { label: i18n.__( 'Categorie', 'kndsb' ), value: a.categoryId, options: options, onChange: function ( value ) { props.setAttributes( { categoryId: Number( value ) } ); } } ),
			el( TextControl, { label: i18n.__( 'Linktekst', 'kndsb' ), value: a.linkText, onChange: function ( value ) { props.setAttributes( { linkText: value } ); } } ), el( URLInput, { value: a.linkUrl, onChange: function ( value ) { props.setAttributes( { linkUrl: value } ); } } ), el( ToggleControl, { label: i18n.__( 'Samenvatting tonen', 'kndsb' ), checked: a.showExcerpt, onChange: function ( value ) { props.setAttributes( { showExcerpt: value } ); } } ), el( ToggleControl, { label: i18n.__( 'Lees artikel tonen', 'kndsb' ), checked: a.showReadMore, onChange: function ( value ) { props.setAttributes( { showReadMore: value } ); } } ), el( ToggleControl, { label: i18n.__( 'Meer laden tonen', 'kndsb' ), checked: a.loadMore, onChange: function ( value ) { props.setAttributes( { loadMore: value } ); } } ) ) ),
			el( 'div', blockEditor.useBlockProps(), el( serverSideRender, { block: 'kndsb/news-row', attributes: a } ) ) );
	}, save: function () { return null; } } );
} )( window.wp.blocks, window.wp.blockEditor, window.wp.element, window.wp.components, window.wp.data, window.wp.serverSideRender, window.wp.i18n );
