( function ( blocks, blockEditor, components, element, i18n ) {
	var el = element.createElement, InnerBlocks = blockEditor.InnerBlocks, InspectorControls = blockEditor.InspectorControls, RichText = blockEditor.RichText, PanelBody = components.PanelBody, SelectControl = components.SelectControl, TextControl = components.TextControl;
	var row = [ 'core/group', { className: 'kndsb-sport-page__program-row' }, [ [ 'core/paragraph', { className: 'kndsb-sport-page__program-time', content: '08:00' } ], [ 'core/paragraph', { className: 'kndsb-sport-page__program-name', content: 'Naam wedstrijd of evenement' } ], [ 'core/paragraph', { className: 'kndsb-sport-page__program-location', content: 'Locatie' } ], [ 'core/paragraph', { className: 'kndsb-sport-page__program-tag', content: 'Sport' } ], [ 'core/paragraph', { className: 'kndsb-sport-page__program-arrow', content: '›' } ] ] ];
	var template = [ [ 'core/paragraph', { className: 'kndsb-sport-page__program-day', content: 'Dinsdag 20 oktober' } ], row, [ 'core/paragraph', { className: 'kndsb-sport-page__program-day', content: 'Zaterdag 31 oktober' } ], row ];
	blocks.registerBlockType( 'kndsb/sport-program', {
		edit: function ( props ) { var a = props.attributes; return el( element.Fragment, {}, el( InspectorControls, {}, el( PanelBody, { title: i18n.__( 'Programma-instellingen', 'kndsb' ) }, el( SelectControl, { label: i18n.__( 'Kleur', 'kndsb' ), value: a.colorScheme, options: [ { label: 'Wit', value: 'white' }, { label: 'Oranje', value: 'orange' }, { label: 'Blauw', value: 'blue' }, { label: 'Rood', value: 'red' }, { label: 'Gebroken blauw-wit', value: 'blue-white' } ], onChange: function ( value ) { props.setAttributes( { colorScheme: value } ); } } ), el( TextControl, { label: i18n.__( 'Knoplink', 'kndsb' ), value: a.buttonUrl, onChange: function ( value ) { props.setAttributes( { buttonUrl: value } ); } } ) ) ), el( 'section', blockEditor.useBlockProps( { className: 'kndsb-sport-program kndsb-sport-program--' + a.colorScheme } ), el( 'div', { className: 'kndsb-sport-program__inner' }, el( 'header', { className: 'kndsb-sport-page__section-heading' }, el( RichText, { tagName: 'h2', className: 'kndsb-sport-page__section-title', value: a.title, allowedFormats: [], onChange: function ( value ) { props.setAttributes( { title: value } ); } } ), el( RichText, { tagName: 'span', className: 'kndsb-sport-program__button-label', value: a.buttonText, allowedFormats: [], onChange: function ( value ) { props.setAttributes( { buttonText: value } ); } } ) ), el( InnerBlocks, { template: template, templateLock: false } ) ) ) ); },
		save: function ( props ) { var a = props.attributes; return el( 'section', blockEditor.useBlockProps.save( { className: 'kndsb-sport-program kndsb-sport-program--' + a.colorScheme } ), el( 'div', { className: 'kndsb-sport-program__inner' }, el( 'header', { className: 'kndsb-sport-page__section-heading' }, el( RichText.Content, { tagName: 'h2', className: 'kndsb-sport-page__section-title', value: a.title } ), el( 'a', { className: 'kndsb-sport-program__button', href: a.buttonUrl || '/agenda/' }, el( RichText.Content, { tagName: 'span', value: a.buttonText } ) ) ), el( InnerBlocks.Content ) ) ); }
	} );
} )( window.wp.blocks, window.wp.blockEditor, window.wp.components, window.wp.element, window.wp.i18n );
